### ISSUE TITLE
vulnerabilities

### ISSUE THREAD

**Issue by whydoesthecodenotwork** [sitechtimes/ai-vs-human-art-frontend#13]
![image](https://github.com/user-attachments/assets/68849051-f092-48a5-aae6-eabbd4c3d7a5)
please fix IMMEDIATELY my family is STARVING because of this

**Comment by TinaGu0** [comment]
womp

**Comment by whydoesthecodenotwork** [comment]
![image](https://github.com/user-attachments/assets/f0063357-6257-4266-a60a-d0232896170c)
