### ISSUE TITLE
creating the primevue theme

### ISSUE THREAD

**Issue by wwormseason** [sitechtimes/ai-vs-human-art-frontend#14]
have fun

**Comment by whydoesthecodenotwork** [comment]
![a theme selector, featuring a rainbow of 17 themes and comic sans](https://github.com/user-attachments/assets/852bd1ee-7d49-48a4-8f89-3ca8cf0be500)

**Comment by whydoesthecodenotwork** [comment]
![image](https://github.com/user-attachments/assets/4396c3cd-7d03-4d21-b60b-495bd99ab933)
[inline styles WERE harmed in the making of this.](https://github.com/sitechtimes/ai-vs-human-art-frontend/blob/5b240c48d386fcaa876fa30db8d5e79732a80ba1/frontend/src/components/ThemeComponent.vue#L28)
